# aaa = "bbb"

[[conditions]]
target_url = "https://app.rakuten.co.jp/services/api/Travel/VacantHotelSearch/20170426"
prefecture = "akita"
area = "tazawa"
checkin = "2019-12-01"
checkout = "2019-12-02"
max_charge = 15000
squeeze = [ "kinen", "internet", "onsen", "dinner"]
