[[conditions]]
prefecture = "kanagawa"
area = "yugawara"
checkin = "2019-11-22"
checkout = "2019-11-23"
max_charge = 15000
# squeeze = [ "kinen", "internet", "onsen", "dinner"]
squeeze = [ "onsen", "dinner"]

[[conditions]]
prefecture = "kanagawa"
area = "hakone"
checkin = "2019-11-22"
checkout = "2019-11-23"
max_charge = 15000
squeeze = [ "onsen", "dinner"]
